const fs = require('fs');
const path = require('path');

const dictionary = {
  '>Home<': '>Trang chủ<',
  '>Marketplace<': '>Chợ<',
  '>Profile<': '>Hồ sơ<',
  '>Settings<': '>Cài đặt<',
  '>Tasks<': '>Nhiệm vụ<',
  '>Dashboard<': '>Bảng điều khiển<',
  '>Login<': '>Đăng nhập<',
  '>Register<': '>Đăng ký<',
  '>Email<': '>Email<',
  '>Password<': '>Mật khẩu<',
  '>Forgot Password?<': '>Quên mật khẩu?<',
  '>Sign In<': '>Đăng nhập<',
  '>Sign Up<': '>Đăng ký<',
  '>Create Account<': '>Tạo tài khoản<',
  '>Full Name<': '>Họ và tên<',
  ">Don't have an account?<": '>Chưa có tài khoản?<',
  ">Already have an account?<": '>Đã có tài khoản?<',
  '>Logout<': '>Đăng xuất<',
  '>Search<': '>Tìm kiếm<',
  '>Categories<': '>Danh mục<',
  '>Products<': '>Sản phẩm<',
  '>Orders<': '>Đơn hàng<',
  '>Cart<': '>Giỏ hàng<',
  '>Checkout<': '>Thanh toán<',
  '>Total<': '>Tổng cộng<',
  '>Price<': '>Giá<',
  '>Quantity<': '>Số lượng<',
  '>Add to Cart<': '>Thêm vào giỏ<',
  '>Buy Now<': '>Mua ngay<',
  '>Description<': '>Mô tả<',
  '>Reviews<': '>Đánh giá<',
  '>Status<': '>Trạng thái<',
  '>Action<': '>Hành động<',
  '>Edit<': '>Sửa<',
  '>Delete<': '>Xóa<',
  '>Save<': '>Lưu<',
  '>Cancel<': '>Hủy<',
  '>Create<': '>Tạo mới<',
  '>Update<': '>Cập nhật<',
  '>Submit<': '>Xác nhận<',
  '>Vendor Dashboard<': '>Bảng điều khiển Người bán<',
  '>Admin Dashboard<': '>Bảng điều khiển Quản trị<',
  '>Overview<': '>Tổng quan<',
  '>Revenue<': '>Doanh thu<',
  '>Users<': '>Người dùng<',
  '>View All<': '>Xem tất cả<',
  '>Notification<': '>Thông báo<',
  '>Messages<': '>Tin nhắn<',
  '>Chat<': '>Nhắn tin<',
  '>My Orders<': '>Đơn hàng của tôi<',
  '>Track Order<': '>Theo dõi đơn<',
  '>Completed<': '>Hoàn thành<',
  '>Pending<': '>Chờ xử lý<',
  '>Processing<': '>Đang xử lý<',
  '>Delivered<': '>Đã giao<',
  '>Cancelled<': '>Đã hủy<',
  '>Recent Transactions<': '>Giao dịch gần đây<',
  '>Balance<': '>Số dư<',
  '>Expense Management<': '>Quản lý chi tiêu<',
  '>Budget<': '>Ngân sách<',
  '>Analytics<': '>Phân tích<',
  '>Welcome<': '>Chào mừng<',
  '>Vendor Shop<': '>Cửa hàng<',
  'placeholder="Search': 'placeholder="Tìm kiếm',
  'placeholder="Email': 'placeholder="Email',
  'placeholder="Password': 'placeholder="Mật khẩu',
  'placeholder="Full Name': 'placeholder="Họ và tên',
  'placeholder="Enter': 'placeholder="Nhập',
  '>Loading...<': '>Đang tải...<',
  '>All Products<': '>Tất cả sản phẩm<',
  '>By Vendor<': '>Theo người bán<',
  '>No products found<': '>Không tìm thấy sản phẩm nào<',
  '>No vendors found<': '>Không tìm thấy người bán nào<',
  '>Try adjusting your filters<': '>Thử điều chỉnh bộ lọc của bạn<',
  '>Try a different search term<': '>Thử từ khóa khác<',
  '>No vendors have products yet<': '>Chưa có người bán nào có sản phẩm<',
  '>Loading products...<': '>Đang tải sản phẩm...<',
  '>Loading recommendations...<': '>Đang tải gợi ý...<',
  '>No recommendations available<': '>Không có gợi ý nào<',
  '>Unable to load recommendations<': '>Không thể tải gợi ý<',
  '>In Stock<': '>Còn hàng<',
  '>Out of Stock<': '>Hết hàng<',
  '>Recommended for You<': '>Gợi ý cho bạn<',
  '>Filter<': '>Lọc<',
  '>Sort<': '>Sắp xếp<',
  '>Newest First<': '>Mới nhất<',
  '>Oldest First<': '>Cũ nhất<',
  '>Price: Low to High<': '>Giá: Thấp đến Cao<',
  '>Price: High to Low<': '>Giá: Cao đến Thấp<',
  '>Name: A to Z<': '>Tên: A đến Z<',
  '>Name: Z to A<': '>Tên: Z đến A<',
  '>Apply Filters<': '>Áp dụng bộ lọc<',
  '>Reset<': '>Đặt lại<',
  '>Apply Sort<': '>Áp dụng sắp xếp<',
  '>Close<': '>Đóng<',
  '>System Status<': '>Trạng thái hệ thống<',
  '>Running normally<': '>Hoạt động bình thường<',
  '>Security<': '>Bảo mật<',
  '>Secure<': '>An toàn<',
  '>Revenue last 7 days<': '>Doanh thu 7 ngày qua<',
  '>New Users<': '>Người dùng mới<',
  '>My Sales (Admin Store)<': '>Doanh số của tôi<',
  '>Total Users<': '>Tổng số người dùng<',
  '>Transactions<': '>Giao dịch<',
  '>Total Balance<': '>Tổng số dư<',
  '>Total Orders<': '>Tổng số đơn hàng<',
  '>Revenue (Coins)<': '>Doanh thu (Xu)<',
  '>Revenue (VND)<': '>Doanh thu (VNĐ)<',
  '>Create Savings Goal<': '>Tạo mục tiêu tiết kiệm<',
  '>Goal Title<': '>Tên mục tiêu<',
  '>Target Amount (xu)<': '>Số tiền mục tiêu (xu)<',
  '>Filter Products<': '>Lọc sản phẩm<',
  '>Price Range<': '>Khoảng giá<',
  '>Min<': '>Thấp nhất<',
  '>Max<': '>Cao nhất<',
  '>Stock Status<': '>Trạng thái kho<',
  '>In Stock Only<': '>Chỉ hiển thị còn hàng<',
  '>Apply<': '>Áp dụng<',
  '>Sort By<': '>Sắp xếp theo<',
  '>Active now<': '>Đang hoạt động<',
  '>No messages yet<': '>Chưa có tin nhắn<',
  '>Start the conversation!<': '>Bắt đầu cuộc trò chuyện!<',
  '>Chat with other users or sellers!<': '>Trò chuyện với người dùng hoặc người bán!<',
  '>Create new message<': '>Tạo tin nhắn mới<',
  '>New Message<': '>Tin nhắn mới<',
  '>Start typing to search...<': '>Bắt đầu nhập để tìm kiếm...<',
  '>Communication<': '>Giao tiếp<',
  '>Activities<': '>Hoạt động<',
  '>Tools & Settings<': '>Công cụ & Cài đặt<',
  '>Max per day:<': '>Tối đa mỗi ngày:<',
  '>Cooldown (minutes):<': '>Thời gian chờ (phút):<',
  '>Done<': '>Xong<',
  '>Loading preferences...<': '>Đang tải tuỳ chọn...<',
  '>Notification Settings<': '>Cài đặt thông báo<',
  '>System Notification Types<': '>Loại thông báo hệ thống<',
  '>Notifications<': '>Thông báo<',
  '>Mark all read<': '>Đánh dấu đã đọc<',
  '>Loading notifications...<': '>Đang tải thông báo...<',
  '>No notifications<': '>Không có thông báo<',
  '>You have read all notifications!<': '>Bạn đã đọc tất cả thông báo!<',
  '>Personal Information<': '>Thông tin cá nhân<',
  '>Phone Number<': '>Số điện thoại<',
  '>Date of Birth<': '>Ngày sinh<',
  '>Address<': '>Địa chỉ<',
  '>Bio<': '>Tiểu sử<',
  '>Transaction History<': '>Lịch sử giao dịch<',
  '>My Cart<': '>Giỏ hàng của tôi<',
  '>System Notifications<': '>Thông báo hệ thống<',
  '>Help & Support<': '>Trợ giúp & Hỗ trợ<',
  '>Share<': '>Chia sẻ<',
  '>Like<': '>Thích<',
  '>Reply<': '>Trả lời<',
  '>Comments<': '>Bình luận<',
  '>Write a comment...<': '>Viết bình luận...<',
  '>Add Comment<': '>Thêm bình luận<',
  '>Post Comment<': '>Đăng bình luận<',
  '>Discussion Board<': '>Bảng thảo luận<',
  '>No posts yet<': '>Chưa có bài viết nào<',
  '>Be the first to share something!<': '>Hãy là người đầu tiên chia sẻ!<',
  '>Create Post<': '>Tạo bài viết<',
  '>Post<': '>Đăng<',
  '>Report Content<': '>Báo cáo nội dung<',
  '>Reason<': '>Lý do<',
  '>Description (optional)<': '>Mô tả (tuỳ chọn)<',
  '>Submit Report<': '>Gửi báo cáo<',
  '>Claimed<': '>Đã nhận<',
  '>Claim Reward<': '>Nhận thưởng<',
  '>Start Now<': '>Bắt đầu ngay<',
  '>Earn Coins Challenges<': '>Thử thách kiếm xu<',
  '>Complete challenges to earn Shopee Coins!<': '>Hoàn thành thử thách để kiếm xu!<',
  '>Available<': '>Có sẵn<',
  '>No tasks available at this time<': '>Không có nhiệm vụ nào vào lúc này<',
  '>Top Up Coins<': '>Nạp xu<',
  '>Payment Method<': '>Phương thức thanh toán<',
  '>Coin Packages<': '>Gói xu<',
  '>No coin packages available at this time.<': '>Không có gói xu nào vào lúc này.<',
  '>Overview of business activities<': '>Tổng quan hoạt động kinh doanh<',
  '>Current Package:<': '>Gói hiện tại:<',
  '>Upgrade<': '>Nâng cấp<',
  '>Products listed this week<': '>Sản phẩm đã đăng trong tuần<',
  '>You have reached your listing limit for this week. Please upgrade your package to list more.<': '>Bạn đã đạt giới hạn đăng sản phẩm trong tuần. Vui lòng nâng cấp gói để đăng thêm.<',
  '>Total revenue (VND)<': '>Tổng doanh thu (VNĐ)<',
  '>Buyers use coins<': '>Người mua sử dụng xu<',
  '>coins<': '>xu<',
  '>Total Orders<': '>Tổng đơn hàng<',
  '>Pending Orders<': '>Đơn chờ xử lý<',
  '>Total Products<': '>Tổng số sản phẩm<',
  '>Quick Access<': '>Truy cập nhanh<',
  '>Order Management<': '>Quản lý đơn hàng<',
  '>My Products<': '>Sản phẩm của tôi<',
  '>Revenue:<': '>Doanh thu:<',
  '>Listing Packages<': '>Gói đăng tin<',
  '>Upgrade Your Store<': '>Nâng cấp Cửa hàng<',
  '>List more products, reach more customers<': '>Đăng nhiều sản phẩm hơn, tiếp cận nhiều khách hàng hơn<',
  '>Free Package (Current)<': '>Gói Miễn phí (Hiện tại)<',
  '>1 product / week<': '>1 sản phẩm / tuần<',
  '>Max 1 category<': '>Tối đa 1 danh mục<',
  '>/ month<': '>/ tháng<',
  '>Subscribe now<': '>Đăng ký ngay<',
  '>Manage inventory<': '>Quản lý kho<',
  '>Listing limit this week<': '>Giới hạn đăng tin tuần này<',
  '>Product Price (VND) *<': '>Giá sản phẩm (VNĐ) *<',
  '>Set Discount<': '>Cài đặt giảm giá<',
  '>Discount % (0-100)<': '>Giảm giá % (0-100)<',
  '>Price after discount:<': '>Giá sau khi giảm:<',
  '>My Products<': '>Sản phẩm của tôi<',
  '>Listing limit this week<': '>Giới hạn đăng tin tuần này<',
  '>No products found.<': '>Không tìm thấy sản phẩm nào.<',
  "'Edit Product'": "'Sửa sản phẩm'",
  "'Create Product'": "'Tạo sản phẩm'",
  '>Product Name *<': '>Tên sản phẩm *<',
  '>Category<': '>Danh mục<',
  "'Update'": "'Cập nhật'",
  "'Save Product'": "'Lưu sản phẩm'",
  '>Set Discount<': '>Cài đặt giảm giá<',
  '>Listing Packages<': '>Gói đăng tin<',
  '>List more products, reach more customers<': '>Đăng nhiều sản phẩm hơn, tiếp cận nhiều khách hàng hơn<',
  '>Free Package (Current)<': '>Gói Miễn phí (Hiện tại)<',
  "'Customer'": "'Khách hàng'",
  '>No orders yet<': '>Chưa có đơn hàng nào<',
  '>Loading analytics data...<': '>Đang tải dữ liệu phân tích...<',
  '>Overview of business activities<': '>Tổng quan hoạt động kinh doanh<',
  'Current Package:': 'Gói hiện tại:',
  '>Products listed this week<': '>Sản phẩm đã đăng trong tuần<',
  '>Total revenue (VND)<': '>Tổng doanh thu (VNĐ)<',
  '>Buyers use coins<': '>Người mua sử dụng xu<',
  '>Total Orders<': '>Tổng số đơn hàng<',
  '>Pending Orders<': '>Đơn chờ xử lý<',
  '>Total Products<': '>Tổng số sản phẩm<',
  '>Quản lý kho<': '>Quản lý kho<', // Already VI but to be safe
};

function processDirectory(dirPath) {
  const files = fs.readdirSync(dirPath);
  
  for (const file of files) {
    const fullPath = path.join(dirPath, file);
    const stat = fs.statSync(fullPath);
    
    if (stat.isDirectory()) {
      processDirectory(fullPath);
    } else if (fullPath.endsWith('.tsx') || fullPath.endsWith('.ts')) {
      let content = fs.readFileSync(fullPath, 'utf8');
      let originalContent = content;
      
      for (const [eng, vie] of Object.entries(dictionary)) {
        const escapedEng = eng.replace(/[-[\]{}()*+?.,\\\\^$|#\\s]/g, '\\\\$&');
        const regex = new RegExp(escapedEng, 'g');
        content = content.replace(regex, vie);
      }
      
      if (content !== originalContent) {
        fs.writeFileSync(fullPath, content, 'utf8');
        console.log(`Translated file: ${fullPath}`);
      }
    }
  }
}

processDirectory(path.join(__dirname, '../src'));
